using Test, Aqua, BoundaryIntegralEquations

Aqua.test_undefined_exports(BoundaryIntegralEquations)
Aqua.test_persistent_tasks(BoundaryIntegralEquations)
Aqua.test_project_extras(BoundaryIntegralEquations)
Aqua.test_unbound_args(BoundaryIntegralEquations)
Aqua.test_deps_compat(BoundaryIntegralEquations)
Aqua.test_ambiguities(BoundaryIntegralEquations)
Aqua.test_stale_deps(BoundaryIntegralEquations)
Aqua.test_piracies(BoundaryIntegralEquations)
