name = "IntegralEquations"
uuid = "ebf54fa4-afc0-484a-8ee1-77aaf84d33dc"
authors = ["Mikkel Paltorp Schmitt"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
